= ThreeJS fundamentals

A short talk on the basics of THREE js.

== Slides and Examples

These require the asciidoctor plugin to render properly in chrome or firefox. They give a short overview of the most important classes and some typical beginners mistakes.

They are designed to be mixed with viewing the code from the html pages in the following order:

* slide1.adoc
* slide2.adoc
* empty.html (renderer.setClearColor can be used to show it does something)
* slide3.adoc
* objects.html (play around a bit with camera and geometry values, maybe load a texture onto it)
* slide4.adoc
* slide5.adoc
* light.html (play around with material, intensity, positioning etc.)

== Small Movie

As an outlook, a small movie can be found in movingCamera.html; this can be done almost entirely with the few topics covered here.

== Technical note

The examples should run in firefox just fine. Because Chrome is more picky about loading files from the local file system, the examples will need to be served by a small Web server (e.g. the python SimpleHTTPServer), or chrome started with the "--allow-file-access-from-files" flag.